{% set version = "0.26.3" %}
# from languages/python/oso/Makefile
{% set cffi_version_from_makefile = ">=1.15,<2" %}

package:
  name: oso
  version: {{ version }}

source:
  url: https://github.com/osohq/oso/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 53ee9fff6f8addcc797f5d9584eb951d91b785bc65d7d87875b41bb4773914d4
  patches:
    - 0000-no-pip-install-makefile.patch

build:
  number: 0

requirements:
  build:
    - cffi                                   # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make                                   # [build_platform != target_platform]
    - openssl                                # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - clangdev                               # [not osx and build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust >=1.46
    - cargo-bundle-licenses
  host:
    - make
    - clangdev  # [not osx]
    - openssl
    - python
    - pip
    - cffi {{ cffi_version_from_makefile }}
  run:
    - python
    - cffi {{ cffi_version_from_makefile }}

test:
  source_files:
    - languages/python/oso/tests
  imports:
    - oso
    - polar
  commands:
    - pip check
    # must be run from this folder because of hard-coded paths in tests
    - cd languages/python/oso && pytest tests -vv --cov=oso --cov=polar --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=84 -k "not test_parser_errors and not test_repr_when_logging"
  requires:
    - pip
    - pytest-cov
    - ruamel_yaml
    - sqlalchemy

about:
  home: https://github.com/osohq/oso
  summary: Oso is a batteries-included framework for building authorization in your application.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.osohq.com
  dev_url: https://github.com/osohq/oso

extra:
  recipe-maintainers:
    - alexpilot11
    - bollwyvl
