{% set version = "0.27.3" %}
# from languages/python/oso/requirements.txt
{% set cffi_version = "cffi >=1.15,<2" %}

package:
  name: oso
  version: {{ version }}

source:
  url: https://github.com/osohq/oso/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1a93ad45e1b8d249c1080a98c4c1ff318d28cfd8450ba36ce459834d7d7cb95a
  patches:
    - 0000-no-pip-install-makefile.patch

build:
  number: 1
  skip: true  # [aarch64 or ppc64le]

requirements:
  build:
    - {{ cffi_version }}                     # [build_platform != target_platform]
    - openssl                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make                                   # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - clangdev                               # [not osx and build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # from README.md
    - rust >=1.46,<1.70
    - cargo-bundle-licenses
  host:
    - {{ cffi_version }}
    - make
    - clangdev  # [not osx]
    - openssl
    - python
    - pip
  run:
    - python
    - {{ cffi_version }}
    - openssl

test:
  source_files:
    - languages/python/oso/tests
  imports:
    - oso
    - polar
  commands:
    - pip check
    - mypy -p oso --ignore-missing-imports
    # %PREFIX%\lib\site-packages\polar\build.py:19: error: Need type annotation for "libs" (hint: "libs: List[<type>] = ...")  [var-annotated]
    - mypy -p polar --ignore-missing-imports  # [not win]
    # must be run from this folder because of hard-coded paths in tests
    - cd languages/python/oso && pytest tests -vv --cov=oso --cov=polar --no-cov-on-fail --cov-report=term-missing:skip-covered -k "not test_parser_errors and not test_repr_when_logging" --cov-fail-under=86
  requires:
    - mypy
    - pip
    - pytest-cov
    - ruamel_yaml
    - sqlalchemy

about:
  home: https://github.com/osohq/oso
  summary: Oso is a batteries-included framework for building authorization in your application.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.osohq.com
  dev_url: https://github.com/osohq/oso

extra:
  recipe-maintainers:
    - alexpilot11
    - bollwyvl
